---
development:
  cloud_name: vidgeo
  api_key: '355933894898387'
  api_secret: nZ_-OkdB_BVlbn8Ab8zd6OzweAs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: vidgeo
  api_key: '355933894898387'
  api_secret: nZ_-OkdB_BVlbn8Ab8zd6OzweAs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: vidgeo
  api_key: '355933894898387'
  api_secret: nZ_-OkdB_BVlbn8Ab8zd6OzweAs
  enhance_image_tag: true
  static_image_support: false
